package com.venkat;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class MapVsFlatMap {

	public static void main(String[] args) {
		MapVsFlatMap demo = new MapVsFlatMap();
		demo.mapDemo();
		demo.flapMapDemo();
	}
	
	public void mapDemo() {
		ArrayList<String> fruit = new ArrayList<>();
        fruit.add("Apple");
        fruit.add("mango");
        fruit.add("pineapple");
        fruit.add("kiwi");
        
        System.out.println("List of fruit-" + fruit);
        
        List<Integer> list = fruit.stream()
        		.map(s -> s.length())
        		.collect(Collectors.toList());
        System.out.println("List generated by map-" + list);
	}

	public void flapMapDemo() {
		List<List<Integer> > number = new ArrayList<>();
		number.add(Arrays.asList(1, 2));
        number.add(Arrays.asList(3, 4));
        number.add(Arrays.asList(5, 6));
        number.add(Arrays.asList(7, 8));
        
        List<Integer> flatList = number.stream()
        	.flatMap(list -> list.stream())
        	.collect(Collectors.toList());
        System.out.println("List generate by flatMap-" + flatList);
	}
}
